version: '3.2'

services:
    alastair:
        build:
            context: ./$PATH_ALASTAIR/alastair/
            dockerfile: ./Dockerfile.dev
        image: aegee/alastair:dev
        volumes:
            - ./$PATH_ALASTAIR/../:/usr/src/myapp
        depends_on:
            - postgres-alastair
        expose:
            - "4000"
        labels:
            - "traefik.frontend.rule=HostRegexp:{domain:[a-z0-9.]+};PathPrefix:/services/alastair;PathPrefixStrip:/services/alastair"
            - "traefik.frontend.priority=100"
            - "traefik.port=4000"
            - "traefik.backend=alastair"
            - "traefik.enable=true"
            - "registry.modules=/static/getModules.json"
            - "registry.status=/status"

    postgres-alastair:
        image: postgres:latest
        volumes:
            - postgres-alastair:/var/lib/postgresql/data
        expose:
            - "5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

volumes:
    postgres-alastair:
        driver: "local"

networks:
  default:
    external:
      name: OMS
